#include <iostream>
#include <string>

using namespace std;

int main() {
    string a;
    
    while (true) {
        cout << "Enter your word (or type 'EXIT' to quit): ";
        cin>> a;
        
        if (a == "EXIT") {
            cout << "Exiting the program." << endl;
            break;
        }
        
        if (a == "DIGITAL_COMPUTER") {
            cout << "These are the modern computer which are capable of processing information in discreate form." << endl;
        } else if (a == "ANALOG_COMPUTER") {
            cout << "These computers are used to process data generated by ongoing physical processes." <<endl;
        } else if (a == "HYBRID_COMPUTER") {
            cout << "These combine both analog and digital technology." <<endl;
        } else if (a == "SUPERCOMPUTER") {
            cout << "These are the most powerful and expensive computers that are used for complex scientific calculations, simulations, and research." <<endl;
        } else if (a == "MAINFRAME_COMPUTER") {
            cout << "These are large and powerful computers that are used by large organizations." <<endl;
        } else if (a == "MINI_COMPUTER") {
            cout << "These are smaller and less powerful than mainframe computers." <<endl;
        } else if (a == "PERSONAL_COMPUTER") {
            cout << "These are small and affordable computers that are designed for individual users." <<endl;
        } else {
            cout << "Sorry, I don't have an explanation for that term." <<endl;
        }
    }
    
    return 0;
}